[package]
authors = ["Kisio Digital <guillaume.pinot@kisio.org>"]
name = "navitia_model"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
csv = "1.0.0"
derivative = "1"
env_logger = "0.5"
log = "0.4"
serde = "1"
serde_derive = "1"
structopt = "0.2"
failure = "0.1.1"
serde_json = "1"
minidom = "0.9.0"
zip = "0.3.2"
tempdir = "0.3.7"
walkdir = "2.1.4"
geo-types = "0.1.1"
wkt = "0.1.2"
gtfs-structures = "0.4.3"

[dependencies.get-corresponding-derive]
path = "get-corresponding-derive"

[workspace]
